= TLS Wizard

This is a GUI app to enable TLS for WildFly.

== How to run the application

Use this application to configure one-way TLS for applications deployed on WildFly. Two-way TLS is WIP.

.Prerequisites

. WildFly is installed.
. Maven is installed.

.Procedure

. Configure management interface to enable JBoss DMR API.

.. Add the following element to `<management-interfaces>` `in standalone.xml`.
+
[source,xml,options="nowrap"]
----
<management-interfaces>
	...
    <!-- Add the following native-interface -->
    <native-interface>
        <socket-binding native="management-native"/>
    </native-interface>
</management-interface>
----

.. Add the following socket binding:
+
[source,xml,options="nowrap"]
----
<socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
	...
	<socket-binding name="management-native" interface="management" port="9999"/>
	...
</socket-binding-group>
---- 

. Start the server.

. Navigate to the directory `tlswizard`.

. Launch this app with the command:
+
[source,options="nowrap"]
----
$ mvn clean javafx:run
----
+
This launches the TLS Wizard.

. Enter the IP for the server. The default is `127.0.0.1` (localhost). For local WildFly deployments, you don't need to update this.   

. Select `One-way TLS` or `Two-way TLS` to configure One-way TLS or Two-way TLS.

. Select `applications` or `management interfaces` to secure applications or management interfaces.

. Click *Next*.

** If you selected `One-way TLS`:
.. Enter a name for the key store to create with `.pkcs12` extension.
.. Enter details for the certificate to be generated. If you don't, all the values are set to `unknown`.
.. Click *Configure TLS*. 
.. Wait till you get a success message.
.. To verify TLS, do this:

***  If you secure applications: 
... Reload the server.
... Navigate to link:https://localhost:8443[]. Inspect the certificate. The `Common Name (CN)` should match the first and last name you entered. 

*** If you secured the management interface:
... Shutdown and start the server.
... Navigate to link:http://localhost:9990[]. You will be redirected to `localhost:9993` Inspect the certificate. The `Common Name (CN)` should match the first and last name you entered.

** That's it! one-way TLS is now enabled.

** If you selected `Two-way TLS`:
*** You are directed to a page with Work in Progress. You can click *Back* to go back to the home page.